on:
  push:
    branches:
      - master
name: Build and Release Web
jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    container: cirrusci/flutter:beta
    steps:
      - uses: actions/checkout@v1
      - run: flutter pub get
      - run: flutter build web
      - name: Push Web Build
        env:
          GITHUB_TOKEN: ${{ secrets.githubtoken }}
          GITHUB_EMAIL: ${{ secrets.email }}
          GITHUB_NAME: ${{ secrets.name }}
        run: |
          git config user.email "${GITHUB_EMAIL}"
          git config user.name "${GITHUB_NAME}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/midiowavending_deploy.git
          git checkout master
          rm -rf .gitignore
          cp CNAME build/web
          git add .
          git commit -m "Building Web"
          git subtree split --prefix build/web -b gh-pages
          git push -f origin gh-pages:gh-pages